### PR TITLE
Use @goto-bus-stop/common-shake

### PR DESCRIPTION
**Pull request by goto-bus-stop**
This fork includes a PR to track dependent uses. That means that,
if an export is used exclusively in unused functions, it will also get
removed.

This is especially helpful for things like `util` and `path`, which have
a lot of interdependent functions that could previously not be removed.
For example, `util.format` was always included because it is used in
other functions in the `util` module, even if the only thing the bundle
used was `util.inherits`.

### CODE REVIEW

**Comment by toddself** [comment]
This fixes #12 for us.  Is there a plan for getting this merged in?

**Comment by goto-bus-stop** [comment]
noted; surprised that this helps with that issue :D will release in a bit

**Comment by toddself** [comment]
Yeah, I figured might as well check out the open PR and re-run
our build.
We ended up forking and fixing sbd so this much lower priority for us,
but nice to know there is a potential solution!
Thanks as ever for your hard work!

On Fri, Apr 27, 2018, at 01:08, Renée Kooi wrote:
> noted; surprised that this helps with that issue :D will release
> in a bit> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/browserify/common-shakeify/pull/14#issuecomment-384897958

**Comment by goto-bus-stop** [comment]
:package: 0.5.0

**Pull request merged**
